name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: avansoft
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/avansoft/flickit-platform-frontend:${{ steps.vars.outputs.tag }} ./frontend
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/avansoft/flickit-platform-frontend:${{ steps.vars.outputs.tag }}